{{- if not (eq .Values.spire.oidcDiscoveryProvider.ingress.operatorManaged "true") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spire-spiffe-oidc-discovery-provider
  namespace: {{ .Release.Namespace }}
  {{- if .Values.spire.server.ingress.annotations }}
  annotations:
  {{- tpl (toYaml .Values.spire.oidcDiscoveryProvider.ingress.annotations) . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ tpl .Values.spire.oidcDiscoveryProvider.ingress.host $ }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.spire.oidcDiscoveryProvider.service.name }}
                port:
                  number: {{ .Values.spire.oidcDiscoveryProvider.service.port }}
{{- end }}