{{- if eq .Values.hardening.etcdEncryption.enabled true }}
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/sync-options: "ServerSideApply=true"
  labels:
    app.kubernetes.io/component: etcd-encryption
spec:
  encryption:
    type: {{ .Values.hardening.etcdEncryption.type }}
{{- end }}

